#!/usr/bin/env node
// Bring the Lleverage design-system kit into a video folder: fonts and logos into brand/, and brand.css (the kit's
// :root tokens plus @font-face rules). The kit is private: it comes from the lleverage-presentations cache
// (run that skill's scripts/sync.sh first). Nothing from it is ever committed to the toolkit.
//   node brand.mjs <dir>
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.resolve(process.argv[2] || ".");
const home = process.env.LLEVERAGE_PRESENTATIONS_HOME || path.join(homedir(), ".cache", "lleverage-presentations");
const kit = path.join(home, "delta-agent/plugins/delta/skills/lleverage-presentations");
const sync = path.resolve(here, "../../lleverage-presentations/scripts/sync.sh");
if (!existsSync(path.join(kit, "system/SYSTEM-VERSION.json"))) {
  console.error(`No brand kit at ${kit}.\nRun: ${sync}`);
  process.exit(2);
}
const out = path.join(dir, "brand");
mkdirSync(out, { recursive: true });
cpSync(path.join(kit, "system/fonts"), path.join(out, "fonts"), { recursive: true, filter: (s) => !s.endsWith(".py") });
cpSync(path.join(kit, "assets/logo"), path.join(out, "logo"), { recursive: true });
const v = JSON.parse(readFileSync(path.join(kit, "system/SYSTEM-VERSION.json"), "utf8"));
const css = readFileSync(path.join(kit, "system/lleverage.css"), "utf8");
const start = css.indexOf(":root{"), end = css.indexOf("\n}", start) + 2;
if (start < 0) { console.error("kit lleverage.css has no :root block; the kit layout changed"); process.exit(1); }
const faces = [["Abhaya Libre", "abhaya-libre-400.woff2", 400], ["Abhaya Libre", "abhaya-libre-500.woff2", 500], ["Abhaya Libre", "abhaya-libre-700.woff2", 700],
  ["Public Sans", "public-sans.woff2", "100 900"], ["Roboto Mono", "roboto-mono.woff2", "100 700"]]
  .filter(([, f]) => existsSync(path.join(out, "fonts", f)))
  .map(([f, file, w]) => `@font-face{font-family:'${f}';src:url('brand/fonts/${file}') format('woff2');font-weight:${w};font-style:normal;font-display:block;}`);
writeFileSync(path.join(dir, "brand.css"), `/* GENERATED by brand.mjs from design-system kit v${v.version} (tokens ${v.tokensDigest}). Do not edit; not for commit. */\n${faces.join("\n")}\n${css.slice(start, end)}\n`);
writeFileSync(path.join(dir, "brand.js"), `// GENERATED by brand.mjs. Logos for the scene kinds.\nMV.brand = { logo: (dark) => \`<img src="brand/logo/logo-full-\${dark ? "light" : "dark"}.svg" alt="Lleverage">\` };\n`);
console.log(`brand/ and brand.css from kit v${v.version} (tokens ${v.tokensDigest})`);
