#!/usr/bin/env node
// Build <dir>/icons.js with exactly the icons a video uses, from your lleverage checkout's node_modules.
// Font Awesome Pro is licensed to Lleverage, so its paths are never committed anywhere public; this generates
// them locally per video. Scans the folder's .js and .html for fa("name"), fa("s:name") (solid) and lu("name")
// (lucide, camelCase), plus the names the component library always needs, and copies integration("slug") logos.
//   node icons.mjs <dir>
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { appRepo } from "./lib/repo.mjs";

const dir = path.resolve(process.argv[2] || ".");
const repo = appRepo();
const req = createRequire(path.join(repo, "apps/app/package.json"));
const reg = req("@fortawesome/pro-regular-svg-icons"), sol = req("@fortawesome/pro-solid-svg-icons");

const ALWAYS_FA = ["faHouse", "faInbox", "faBolt", "faStar", "faFileSpreadsheet", "faChartLine", "faBookOpen", "faPaperPlane", "faChevronDown", "faPlus", "faMicrophone", "s:faArrowUp",
  "s:faCircleCheck", "s:faCircleNotch", "faPenToSquare"];
const ALWAYS_LU = ["arrowUp", "x", "bot", "chevronRight"];
const files = readdirSync(dir, { recursive: true }).filter((f) => /\.(js|html)$/.test(f) && !/(^|\/)(node_modules|brand|out|check)\//.test(f) && f !== "icons.js");
// Comments carry examples like fa("faName"): drop them before scanning.
const src = files.map((f) => readFileSync(path.join(dir, f), "utf8").replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:"'`])\/\/.*$/gm, "$1")).join("\n");
const faNames = new Set(ALWAYS_FA), luNames = new Set(ALWAYS_LU);
// Any quoted Font Awesome name counts: fa("faX"), UI.step(id, "faX", ...), data-fa="s:faX".
for (const m of src.matchAll(/["'`]((?:s:)?fa[A-Z][A-Za-z0-9]+)["'`]/g)) faNames.add(m[1]);
for (const m of src.matchAll(/\blu\(\s*["'`]([a-z][A-Za-z0-9]*)["'`]/g)) luNames.add(m[1]);

const FA = {}, missing = [];
for (const n of faNames) {
  const solid = n.startsWith("s:"), icon = (solid ? sol : reg)[solid ? n.slice(2) : n];
  if (!icon) { missing.push(n); continue; }
  const [w, h, , , d] = icon.icon; FA[n] = [w, h, Array.isArray(d) ? d.join(" ") : d];
}
// lucide-react ships each icon as [tag, attrs] pairs.
const lucideDir = path.join(path.dirname(req.resolve("lucide-react/package.json")), "dist/esm/icons");
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/([a-z])([0-9])/g, "$1-$2").toLowerCase();
const LU = {};
for (const n of luNames) {
  let text;
  try { text = readFileSync(path.join(lucideDir, kebab(n) + ".js"), "utf8"); } catch { missing.push("lu:" + n); continue; }
  const m = text.match(/__iconNode = (\[[\s\S]*?\]);/) || text.match(/createLucideIcon\("[^"]+", (\[[\s\S]*?\])\);/);
  const nodes = Function(`return ${m[1]}`)();
  LU[n] = nodes.map(([tag, a]) => `<${tag} ${Object.entries(a).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ")}/>`).join("");
}
writeFileSync(path.join(dir, "icons.js"), `// GENERATED by icons.mjs from ${path.basename(repo)} node_modules. Font Awesome Pro: licensed, never commit.
const FA = ${JSON.stringify(FA)};
const LU = ${JSON.stringify(LU)};
function fa(name, cls = "", style = "") { const i = FA[name]; if (!i) { console.error("icon missing: " + name + " (run icons.mjs)"); return ""; } return \`<svg class="fa \${cls}" style="\${style}" viewBox="0 0 \${i[0]} \${i[1]}" fill="currentColor" aria-hidden="true"><path d="\${i[2]}"/></svg>\`; }
function lu(name, cls = "", style = "") { const i = LU[name]; if (!i) { console.error("icon missing: lu " + name + " (run icons.mjs)"); return ""; } return \`<svg class="lu \${cls}" style="\${style}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${i}</svg>\`; }
`);
// Integration logos: UI.integration("microsoft-outlook") → apps/app/public/images/integrations/<slug>.png.
const logos = new Set([...src.matchAll(/integration\(\s*["'`]([a-z0-9-]+)["'`]/g)].map((m) => m[1]));
for (const slug of logos) {
  const from = path.join(repo, "apps/app/public/images/integrations", slug + ".png");
  if (!existsSync(from)) { missing.push("integration:" + slug); continue; }
  mkdirSync(path.join(dir, "integrations"), { recursive: true });
  copyFileSync(from, path.join(dir, "integrations", slug + ".png"));
}
console.log(`icons.js: ${Object.keys(FA).length} Font Awesome, ${Object.keys(LU).length} lucide, ${logos.size} integration logos${missing.length ? `; NOT FOUND: ${missing.join(", ")}` : ""}`);
if (missing.length) process.exit(1);
